# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dev_deployment_artifacts: True
dotenv: .env
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: False
  ganache:
    verify: False
  kovan:
    verify: True
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136'
    dai_usd_price_feed: '0x777A68032a88E5A84678A77Af2CD65A7b3c0775a'
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}

  # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
